### ISSUE TITLE
Add social sharing actions

### ISSUE THREAD

**Issue by anthonygraignic** [Boavizta/datavizta#47]
Add to the current Share button
![image](https://user-images.githubusercontent.com/12660783/177962464-d6ae7e72-32f9-4518-89c6-2fde89571b6e.png)

social networks and icons:
![image](https://user-images.githubusercontent.com/12660783/177967285-43ce9ede-a770-4266-a64c-14ab7bff52d3.png)
(from https://www.websiteplanet.com/fr/webtools/sharelink/)

The modification should only add links, no library.

- [Twitter](https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/guides/web-intent) 
- [Facebook](https://developers.facebook.com/docs/sharing/web/)
- Support [mobile sharing UI](https://web.dev/web-share/)
- [LinkedIn]() ???

---
## Share parameters:

Text: (proposed)
> "I just calculated my IT equipment carbon impact on [Dataviz by Boavizta](https://dataviz.boavizta.org/)

Url (existing one):
> https://dataviz.boavizta.org?lifetime=4.53

**Comment by AirLoren** [comment]
No interest since manufacturers data page is removed
