### ISSUE TITLE
Highlight on the pie chart 

### ISSUE THREAD

**Issue by odelcroi** [Boavizta/datavizta#50]
I've been sharing ideas with designer friends. 

One of them came with the idea of making more visible the pie chart, which is the "result" expected by the data explorer. Something like that on desktop : 

![Screenshot 2022-07-11 at 13 53 00](https://user-images.githubusercontent.com/4077729/179190390-4afd6816-b909-4b5c-97cb-4fa07b027951.png)

Do you think users will be more confortable with such a design?

**Comment by AirLoren** [comment]
pie chart is now above the datagrid
Do you think it's enough to make the pie chart more visible?

**Comment by AirLoren** [comment]
No interest since manufacturers data page is removed
