### ISSUE TITLE
Cloud instances: embedded impacts correspond to the entire physical server regardless instance type

### ISSUE THREAD

**Issue by demeringo** [Boavizta/datavizta#67]
Hi,

Not sure if it it a bug or a design choice ?

When I select an instance type (c5.large) the embedded impacts (manufacture) returned seem to be the embedded impacts of the underlying bare metal instance (c5.metal).

This figure never change wether I select C5.4xlarge or C5.18xlarge (but changes if we change the instance family, still displaying the value corresponding to the metal instance of the new family).

In BoaviztaAPI (at least in V1.1.0) behavior differ, we are attributed a "part" of the corresponding metal instance.

**Comment by demeringo** [comment]
Tested on https://dataviz.boavizta.org/cloudimpact

**Comment by AirLoren** [comment]
Thanks @demeringo. Embbeded impacts are now divided by the number of instances on bare metal server
https://github.com/Boavizta/datavizta/commit/f2c86e82a7bd133707db4eae2bedae67902723ed
